default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 50000
  template: template1
  host: <%= ENV['DB_HOST'] %>
  username: <%= ENV['DB_USER'] %>
  password: <%= ENV['DB_PASSWORD'] %>
development:
  <<: *default
  database: schedule_reminders_dev
test:
  <<: *default
  database: schedule_reminders_test
production:
  <<: *default
  database: <%= ENV.fetch('DB_DATABASE') { 'caretrak_production' } %>
